# Generated by Django 5.1.1 on 2024-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blogs'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_authors'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Random query'),
        ),
    ]
