# Generated by Django 5.1.1 on 2024-09-17 12:06

import uuid
from django.db import migrations, models
import uuid


def generate_unique_ids(apps, schema_editor):
    BlogPost = apps.get_model("blogs", "BlogPost")
    for blog_post in BlogPost.objects.all():
        if not blog_post.unique_id:
            blog_post.unique_id = uuid.uuid4()
            blog_post.save(update_fields=["unique_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_remove_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(
            generate_unique_ids, reverse_code=migrations.RunPython.noop
        ),
    ]
