# Generated by Django 5.1.1 on 2024-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
